CREATE DATABASE IF NOT EXISTS erhanive;
USE erhanive;

CREATE TABLE IF NOT EXISTS users (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  role ENUM('owner','admin','client') NOT NULL DEFAULT 'owner',
  status ENUM('pending','approved','rejected') NOT NULL DEFAULT 'pending',
  name VARCHAR(128) NOT NULL,
  email VARCHAR(128) NOT NULL UNIQUE,
  phone VARCHAR(64) DEFAULT NULL,
  password_hash VARCHAR(255) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS listings (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  owner_id BIGINT UNSIGNED DEFAULT NULL,
  property_type ENUM('apartment','house','land','office','shop') NOT NULL,
  listing_type ENUM('rent','sale') NOT NULL,
  title VARCHAR(255) NOT NULL,
  location VARCHAR(255) NOT NULL,
  price DECIMAL(12,2) NOT NULL,
  size VARCHAR(64) DEFAULT NULL,
  bedrooms INT DEFAULT NULL,
  bathrooms INT DEFAULT NULL,
  toilets INT DEFAULT NULL,
  land_size VARCHAR(64) DEFAULT NULL,
  plot_number VARCHAR(64) DEFAULT NULL,
  zoning VARCHAR(128) DEFAULT NULL,
  land_description TEXT DEFAULT NULL,
  owner_name VARCHAR(128) DEFAULT NULL,
  owner_phone VARCHAR(64) DEFAULT NULL,
  owner_email VARCHAR(128) DEFAULT NULL,
  owner_whatsapp VARCHAR(64) DEFAULT NULL,
  bedroom_condition VARCHAR(255) DEFAULT NULL,
  bathroom_condition VARCHAR(255) DEFAULT NULL,
  toilet_condition VARCHAR(255) DEFAULT NULL,
  dining_condition VARCHAR(255) DEFAULT NULL,
  status ENUM('Draft','Pending Payment','Submitted','Approved','Rejected') NOT NULL DEFAULT 'Submitted',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (owner_id) REFERENCES users(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS listing_images (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  listing_id BIGINT UNSIGNED NOT NULL,
  label VARCHAR(64) NOT NULL,
  url TEXT NOT NULL,
  is_required TINYINT(1) NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (listing_id) REFERENCES listings(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS listing_documents (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  listing_id BIGINT UNSIGNED NOT NULL,
  doc_type ENUM('id_document','land_title','utility_bill') NOT NULL,
  url TEXT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (listing_id) REFERENCES listings(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS payments (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  listing_id BIGINT UNSIGNED DEFAULT NULL,
  user_id BIGINT UNSIGNED DEFAULT NULL,
  payment_type ENUM('connection_fee','listing_submission') NOT NULL DEFAULT 'connection_fee',
  amount DECIMAL(12,2) NOT NULL,
  currency VARCHAR(16) NOT NULL DEFAULT 'MWK',
  method VARCHAR(32) DEFAULT NULL,
  status ENUM('Pending','Paid','Failed') NOT NULL DEFAULT 'Pending',
  provider_ref VARCHAR(128) DEFAULT NULL,
  paid_at TIMESTAMP NULL DEFAULT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS message_threads (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  thread_type ENUM('owner_contact','support') NOT NULL,
  status ENUM('open','closed') NOT NULL DEFAULT 'open',
  subject VARCHAR(255) DEFAULT NULL,
  listing_id BIGINT UNSIGNED DEFAULT NULL,
  client_user_id BIGINT UNSIGNED DEFAULT NULL,
  owner_user_id BIGINT UNSIGNED DEFAULT NULL,
  created_by_user_id BIGINT UNSIGNED NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (listing_id) REFERENCES listings(id) ON DELETE SET NULL,
  FOREIGN KEY (client_user_id) REFERENCES users(id) ON DELETE SET NULL,
  FOREIGN KEY (owner_user_id) REFERENCES users(id) ON DELETE SET NULL,
  FOREIGN KEY (created_by_user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS message_entries (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  thread_id BIGINT UNSIGNED NOT NULL,
  sender_user_id BIGINT UNSIGNED DEFAULT NULL,
  sender_role ENUM('client','owner','admin','system') NOT NULL,
  body TEXT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (thread_id) REFERENCES message_threads(id) ON DELETE CASCADE,
  FOREIGN KEY (sender_user_id) REFERENCES users(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS push_tokens (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  user_id BIGINT UNSIGNED NOT NULL,
  expo_push_token VARCHAR(255) NOT NULL,
  device_id VARCHAR(255) DEFAULT NULL,
  platform ENUM('ios','android','web','unknown') NOT NULL DEFAULT 'unknown',
  is_active TINYINT(1) NOT NULL DEFAULT 1,
  last_seen_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uniq_push_token (expo_push_token),
  UNIQUE KEY uniq_user_device (user_id, device_id),
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);
